name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 4"  # cron is UTC, this translates to 10 PM PST Wednesday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceFileLogger, SalesforceHybridSDK]
        macos: [macos-15]
        ios: [^26, ^18, ^17]
        xcode: [^26, ^16, ^15]
        # Valid combinations that will run:
        # - iOS ^26 + Xcode ^26
        # - iOS ^18 + Xcode ^26
        # - iOS ^18 + Xcode ^16
        # - iOS ^17 + Xcode ^15
        exclude:
          - { ios: ^26, xcode: ^16 }
          - { ios: ^26, xcode: ^15 }
          - { ios: ^18, xcode: ^15 }
          - { ios: ^17, xcode: ^26 }
          - { ios: ^17, xcode: ^16 }
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit