name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 4"  # cron is UTC, this translates to 10 PM PST Wednesday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceFileLogger, SalesforceHybridSDK]
        include:
          - macos: macos-15
            ios: ^18
            xcode: ^16
          # - macos: macos-15
          #   ios: ^26
          #   xcode: ^26
          # Note: iOS 26 simulator is not yet available on GitHub runners
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit

  hybrid-samples-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [AccountEditor, MobileSyncExplorerHybrid]
        include:
          - macos: macos-15
            ios: ^18
            xcode: ^16
          # - macos: macos-15
          #   ios: ^26
          #   xcode: ^26
          # Note: iOS 26 simulator is not yet available on GitHub runners
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
      action: build
    secrets: inherit