name: Nightly Tests

on:
  schedule:
    - cron: "30 5 * * 3,5"  # cron is UTC; 9:30 PM PT Tue/Thu.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceFileLogger, SalesforceHybridSDK]
        ios: [^26, ^18]
        include:
          - ios: ^26
            xcode: ^26
          - ios: ^18
            xcode: ^16
    uses: ./.github/workflows/reusable-test-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
    permissions:
      contents: read
      pull-requests: write
    secrets:
      TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  hybrid-samples-nightly:
    strategy:
      fail-fast: false
      matrix:
        app: [AccountEditor, MobileSyncExplorerHybrid]
        ios: [^26, ^18]
        include:
          - ios: ^26
            xcode: ^26
          - ios: ^18
            xcode: ^16
    uses: ./.github/workflows/reusable-build-workflow.yaml
    with:
      app: ${{ matrix.app }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
    permissions:
      contents: read